# .github/workflows/run-cpp.yml
name: Run C++ Code

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile the Code
      run: g++ main.cpp -o main

    - name: Run the Program
      run: ./main

